version: '3'

services: 
    db:
        container_name: db_aula_sexta
        image: mysql
        ports:
            - '3306:3306'
        environment: 
            MYSQL_ROOT_PASSWORD: example
        expose: 
            - '3306'
        volumes:
            - ./.mysql/data:/var/lib/mysql